### ISSUE TITLE
Backend: Update Profile

### ISSUE THREAD

**Issue by tomdu3** [chingu-voyages/v50-tier3-team-21#95]
**__Task Description__**
Update backend Profile

- [ ]
- [ ] a
- [ ] a
- [ ] 

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by ngodi** [comment]
- profile update route
- profile update function and database query
